server:
  port: 9090

    
#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 10Mb  # 最大支持文件大小
      max-request-size: 10Mb #最大支持请求大小
  redis:
    database: 0
    host: 192.168.74.129
    port: 6379
    password: 123456
  mail: 
    host: smtp.163.com
    username: 15837192793@163.com
    password: 1689abc
    default-encoding: UTF-8
  rabbitmq:
    host: 192.168.74.129
    port: 5672
    username: admin
    password: 123456
 
mybatis:
  typeAliasesPackage: com.springboot.mmall.pojo
  mapperLocations: classpath:mappers/*.xml
  
pagehelper:
  propertyName: scott
  
upload:
   filePath: c:/upload
   
filter:
  allow:
     path: /user/login ,/user/get_user_info
     
# yml基本语法的学习，按照空格的层级来控制层级的关系，只要是左对齐的一列数据都是同一层级的，字符串默认不用加上单引号和双引号
# 双引号不会转义特殊字符，特殊字符会作为本身想表示的意思。列如 name : zhangsan \n lisi 输出 zhangsan 换行 lisi
# 单引号会转义特殊字符，特殊字符会显示一个普通的字符串。
# 对象表示如下
person:
  lastname: zhangsan
  age: 20
  maps: {name: scott,password: root}
  lists:
   - cat
   - dog
   - pig
#行内写法
friends01: {lastname: zhangsan,age: 18}

#数组（list，set）,用 -空格 值表示数组中的元素

pets:
  - cat
  - dog
  - pig
#数组的行内写法
pets01: [cat,dog,pig]

mail:
  fromMail:
    addr: 15837192793@163.com


        